name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        PYTHONPATH=. pytest tests/

    - name: Build Docker image
      run: |
        docker build -t ci-pipeline-midterm .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Tag Docker image for Docker Hub
      run: |
        if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
          docker tag ci-pipeline-midterm ${{ secrets.DOCKERHUB_USER }}/ci-pipeline-midterm:dev
        else
          docker tag ci-pipeline-midterm ${{ secrets.DOCKERHUB_USER }}/ci-pipeline-midterm:latest
        fi

    - name: Push Docker image to Docker Hub
      run: |
        if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
          docker push ${{ secrets.DOCKERHUB_USER }}/ci-pipeline-midterm:dev
        else
          docker push ${{ secrets.DOCKERHUB_USER }}/ci-pipeline-midterm:latest
        fi

